import { pinyin } from 'pinyin-pro';
import { HanziGroup } from 'src/app/hanzi.types';

export const data: HanziGroup[] = [
  {
    id: 'body',
    group: '人体部位',
    desc: '包含头，手，口等身体部位相关的汉字。',
    icon: 'fa-solid fa-child',
    character: '身',
    color: '#ff85a2',
    hanzi: [
      {
        character: '人',
        pinyin: pinyin('人'),
        words: ['人民', '工人', '人才'],
        sentence: '我的爸爸是工人。',
        image: 'assets/images/learn/characters/人.png',
      },
      {
        character: '口',
        pinyin: pinyin('口'),
        words: ['口腔', '口才', '人口'],
        sentence: '他高兴的开口大笑了起来。',
        image: 'assets/images/learn/characters/口.png',
      }, {
        character: '牙',
        pinyin: pinyin('牙'),
        words: ['牙齿', '刷牙', '蛀牙'],
        sentence: '小宝宝开心的笑出了两颗可爱的大门牙。',
        image: 'assets/images/learn/characters/牙.png',
      }, {
        character: '耳',
        pinyin: pinyin('耳'),
        words: ['耳朵', '木耳', '耳机'],
        sentence: '小宝宝侧着耳朵，在倾听。',
        image: 'assets/images/learn/characters/耳.png',
      },
      {
        character: '头',
        pinyin: pinyin('头'),
        words: ['头发', '大头', '点头'],
        sentence: '她的头发很长很漂亮。',
        image: 'assets/images/learn/characters/头.png',
      }, {
        character: '手',
        pinyin: pinyin('手'),
        words: ['手指', '手心', '手掌'],
        sentence: '我左手拿了一个苹果。',
        image: 'assets/images/learn/characters/手.png',
      }, {
        character: '目',
        pinyin: pinyin('目'),
        words: ['目光', '目录', '目的'],
        sentence: '他的目光十分坚定，仿佛已经下定决心。',
        image: 'assets/images/learn/characters/目.png',
      },
      {
        character: '舌',
        pinyin: pinyin('舌'),
        words: ['舌头', '舌尖', '舌战'],
        sentence: '小宝宝调皮的吐着舌头，可爱极了。',
        image: 'assets/images/learn/characters/舌.png',
      }, {
        character: '心',
        pinyin: pinyin('心'),
        words: ['心脏', '心术', '心情'],
        sentence: '小宝宝开心的在比心哦。',
        image: 'assets/images/learn/characters/心.png',
      }, {
        character: '足',
        pinyin: pinyin('足'),
        words: ['足球', '充足', '足迹'],
        sentence: '孩子们在操场上快乐的踢足球。',
        image: 'assets/images/learn/characters/足.png',
      }
    ],
  },
  {
    id: 'nature',
    group: '自然现象',
    desc: '包含自然事物相关的汉字。',
    icon: 'fa-solid fa-mountain',
    character: '山',
    color: '#ffd3b5',
    hanzi: [
      {
        character: '日',
        pinyin: pinyin('日'),
        words: ['日出', '日子', '日新月异'],
        sentence: '周末爸爸带我看日出。',
        image: 'assets/images/learn/characters/日.png',
      }, {
        character: '月',
        pinyin: pinyin('月'),
        words: ['月亮', '月光', '花容月貌'],
        sentence: '月光透过窗户照进了我家。',
        image: 'assets/images/learn/characters/月.png',
      }, {
        character: '星',
        pinyin: pinyin('星'),
        words: ['星星', '星座', '星光灿烂'],
        sentence: '夜空中的星星一闪一闪的，好像在眨眼睛。',
        image: 'assets/images/learn/characters/星.png',
      }, {
        character: '光',
        pinyin: pinyin('光'),
        words: ['月光', '光芒', '光怪陆离'],
        sentence: '月光洒在地上，让人感到很温暖。',
        image: 'assets/images/learn/characters/光.png',
      }, {
        character: '水',
        pinyin: pinyin('水'),
        words: ['泉水', '水池', '千山万水'],
        sentence: '这个小河里的水真的很清澈。',
        image: 'assets/images/learn/characters/水.png',
      }, {
        character: '火',
        pinyin: pinyin('火'),
        words: ['火苗', '火焰', '熊熊烈火'],
        sentence: '火是很危险的，我们要小心哦。',
        image: 'assets/images/learn/characters/火.png',
      },
      {
        character: '山',
        pinyin: pinyin('山'),
        words: ['山峰', '高山', '人山人海'],
        sentence: '周末我和爸爸去爬山。',
        image: 'assets/images/learn/characters/山.png',
      }, {
        character: '田',
        pinyin: pinyin('田'),
        words: ['农田', '田野', '沧海桑田'],
        sentence: '农田里种着水稻。',
        image: 'assets/images/learn/characters/田.png',
      }, {
        character: '石',
        pinyin: pinyin('石'),
        words: ['石头', '宝石', '水滴石穿'],
        sentence: '山上有很多的石头。',
        image: 'assets/images/learn/characters/石.png',
      }, {
        character: '土',
        pinyin: pinyin('土'),
        words: ['土地', '泥土', '风土人情'],
        sentence: '我喜欢在泥土里玩耍。',
        image: 'assets/images/learn/characters/土.png',
      }, {
        character: '草',
        pinyin: pinyin('草'),
        words: ['草坪', '草原', '草木皆兵'],
        sentence: '我在草丛中发现了一只可爱的小蜗牛。',
        image: 'assets/images/learn/characters/草.png',
      }, {
        character: '木',
        pinyin: pinyin('木'),
        words: ['木头', '树木', '移花接木'],
        sentence: '这个桌子是用木头做的。',
        image: 'assets/images/learn/characters/木.png',
      }, {
        character: '花',
        pinyin: pinyin('花'),
        words: ['鲜花', '花园', '百花齐放'],
        sentence: '今天的花园里有很多漂亮的花儿。',
        image: 'assets/images/learn/characters/花.png',
      }, {
        character: '鸟',
        pinyin: pinyin('鸟'),
        words: ['小鸟', '候鸟', '鸟语花香'],
        sentence: '小鸟在天空中快乐的飞翔。',
        image: 'assets/images/learn/characters/鸟.png',
      }, {
        character: '虫',
        pinyin: pinyin('虫'),
        words: ['虫子', '毛毛虫', '雕虫小技'],
        sentence: '地上有一条毛毛虫。',
        image: 'assets/images/learn/characters/虫.png',
      }, {
        character: '鱼',
        pinyin: pinyin('鱼'),
        words: ['小鱼', '鱼缸', '如鱼得水'],
        sentence: '我们家养了两条小金鱼。',
        image: 'assets/images/learn/characters/鱼.png',
      },

    ],
  },
  {
    id: 'family',
    group: '家庭关系',
    desc: '包含家庭关系中常用的汉字。',
    icon: 'fa-solid fa-house',
    character: '家',
    color: '#95e1d3',
    hanzi: [
      {
        character: '爸',
        pinyin: pinyin('爸'),
        words: ['爸爸', '老爸', '爸妈'],
        sentence: '我的爸爸很爱我。',
        image: 'assets/images/learn/characters/爸.png',
      }, {
        character: '妈',
        pinyin: pinyin('妈'),
        words: ['妈妈', '老妈', '爸妈'],
        sentence: '我的妈妈很爱我。',
        image: 'assets/images/learn/characters/妈.png',
      }, {
        character: '哥',
        pinyin: pinyin('哥'),
        words: ['哥哥', '帅哥'],
        sentence: '我的哥哥是个小帅哥。',
        image: 'assets/images/learn/characters/哥.png',
      }, {
        character: '弟',
        pinyin: pinyin('弟'),
        words: ['弟弟', '小弟'],
        sentence: '我的弟弟很可爱。',
        image: 'assets/images/learn/characters/弟.png',
      }, {
        character: '姐',
        pinyin: pinyin('姐'),
        words: ['姐姐', '姐妹'],
        sentence: '我的姐姐很漂亮。',
        image: 'assets/images/learn/characters/姐.png',
      }, {
        character: '妹',
        pinyin: pinyin('妹'),
        words: ['妹妹', '姐妹'],
        sentence: '我的妹妹很可爱。',
        image: 'assets/images/learn/characters/妹.png',
      }, {
        character: '爷',
        pinyin: pinyin('爷'),
        words: ['爷爷', '大爷'],
        sentence: '爷爷在河边钓鱼。',
        image: 'assets/images/learn/characters/爷.png',
      }, {
        character: '奶',
        pinyin: pinyin('奶'),
        words: ['奶奶', '牛奶'],
        sentence: '奶奶坐在沙发上织毛衣。',
        image: 'assets/images/learn/characters/奶.png',
      }, {
        character: '姥',
        pinyin: pinyin('姥'),
        words: ['姥姥'],
        sentence: '姥姥做的饭很好吃。',
        image: 'assets/images/learn/characters/姥.png',
      }, {
        character: '舅',
        pinyin: pinyin('舅'),
        words: ['舅舅'],
        sentence: '舅舅给我买了一个小汽车玩具。',
        image: 'assets/images/learn/characters/舅.png',
      }, {
        character: '叔',
        pinyin: pinyin('叔'),
        words: ['叔叔'],
        sentence: '叔叔带我去骑车。',
        image: 'assets/images/learn/characters/叔.png',
      }, {
        character: '伯',
        pinyin: pinyin('伯'),
        words: ['大伯', '伯父'],
        sentence: '大伯总是笑容满面，对我非常和蔼。',
        image: 'assets/images/learn/characters/伯.png',
      }, {
        character: '姑',
        pinyin: pinyin('姑'),
        words: ['姑姑'],
        sentence: '姑姑给我买了一条漂亮的裙子。',
        image: 'assets/images/learn/characters/姑.png',
      }, {
        character: '姨',
        pinyin: pinyin('姨'),
        words: ['姨妈', '阿姨'],
        sentence: '姨妈对我很好，经常给我买好吃的。',
        image: 'assets/images/learn/characters/姨.png',
      }
    ],
  },
  {
    id: 'logic',
    group: '方位逻辑',
    desc: '包含方位和逻辑的相关汉字。',
    icon: 'fa-solid fa-map',
    character: '东',
    color: '#7ccf00',
    hanzi: [
      { character: '东', pinyin: pinyin('东'), words: ['东方', '东边', '日出东方'], sentence: '太阳每天从东方升起。', image: 'assets/images/learn/characters/东.png' },
      { character: '西', pinyin: pinyin('西'), words: ['西方', '西瓜', '日薄西山'], sentence: '夏天我最爱吃西瓜啦。', image: 'assets/images/learn/characters/西.png' },
      { character: '南', pinyin: pinyin('南'), words: ['南方', '指南针', '天南海北'], sentence: '我喜欢吃南方的热带水果。', image: 'assets/images/learn/characters/南.png' },
      { character: '北', pinyin: pinyin('北'), words: ['北方', '北极', '北斗七星'], sentence: '北极有可爱的北极熊。', image: 'assets/images/learn/characters/北.png' },
      { character: '大', pinyin: pinyin('大'), words: ['大象', '大小', '大呼小叫'], sentence: '大象的鼻子长又长。', image: 'assets/images/learn/characters/大.png' },
      { character: '小', pinyin: pinyin('小'), words: ['矮小', '大小', '大材小用'], sentence: '我们家养了一只小仓鼠。', image: 'assets/images/learn/characters/小.png' },
      { character: '上', pinyin: pinyin('上'), words: ['上面', '上学', '后来居上'], sentence: '小鸟在树上欢快的唱歌。', image: 'assets/images/learn/characters/上.png' },
      { character: '下', pinyin: pinyin('下'), words: ['下面', '下午', '居高临下'], sentence: '瀑布从陡峭的山崖上飞泻而下。', image: 'assets/images/learn/characters/下.png' },
      { character: '里', pinyin: pinyin('里'), words: ['里面', '里边', '不远千里'], sentence: '小熊在房子里面。', image: 'assets/images/learn/characters/里.png' },
      { character: '外', pinyin: pinyin('外'), words: ['外面', '窗外', '世外桃源'], sentence: '天气真好，窗外的鸟儿在唱歌。', image: 'assets/images/learn/characters/外.png' },
      { character: '来', pinyin: pinyin('来'), words: ['过来', '回来', '来去无踪'], sentence: '周末邀请我的朋友来我家玩。', image: 'assets/images/learn/characters/来.png' },
      { character: '去', pinyin: pinyin('去'), words: ['过去', '去哪儿', '来去自如'], sentence: '朋友邀请我周末去他家玩。', image: 'assets/images/learn/characters/去.png' },
      { character: '开', pinyin: pinyin('开'), words: ['打开', '开心', '开怀大笑'], sentence: '天气真好，打开窗户透透气。', image: 'assets/images/learn/characters/开.png' },
      { character: '关', pinyin: pinyin('关'), words: ['关闭', '关心', '息息相关'], sentence: '下雨了，关上窗口以防溅水。', image: 'assets/images/learn/characters/关.png' },
      { character: '多', pinyin: pinyin('多'), words: ['很多', '多少', '多才多艺'], sentence: '今天去超市买了很多苹果。', image: 'assets/images/learn/characters/多.png' },
      { character: '少', pinyin: pinyin('少'), words: ['少数', '少量', '少见多怪'], sentence: '小明摘的苹果比我少。', image: 'assets/images/learn/characters/少.png' },
      { character: '远', pinyin: pinyin('远'), words: ['远处', '远方', '远走高飞'], sentence: '他望着远处的山，心里在想着什么。', image: 'assets/images/learn/characters/远.png' },
      { character: '近', pinyin: pinyin('近'), words: ['附近', '近处', '近在咫尺'], sentence: '我家附近的公园里有很多花。', image: 'assets/images/learn/characters/近.png' },
      { character: '高', pinyin: pinyin('高'), words: ['高大', '高超', '高楼大厦'], sentence: '高楼大厦是真的高啊。', image: 'assets/images/learn/characters/高.png' },
      { character: '低', pinyin: pinyin('低'), words: ['高低', '低处', '眼高手低'], sentence: '河水从高处往低处流。', image: 'assets/images/learn/characters/低.png' },
    ],
  },
  {
    id: 'weather',
    group: '天气气候',
    desc: '包含与天气，气候相关的汉字。',
    icon: 'fa-solid fa-sun',
    character: '春',
    color: '#a684ff',
    hanzi: [
      { character: '春', pinyin: pinyin('春'), words: ['春天', '春游', '春光明媚'], sentence: '春天是万物复苏的季节。', image: 'assets/images/learn/characters/春.png' },
      { character: '夏', pinyin: pinyin('夏'), words: ['夏天', '盛夏', '春生夏长'], sentence: '炎热的夏天，吃雪糕真舒服。', image: 'assets/images/learn/characters/夏.png' },
      { character: '秋', pinyin: pinyin('秋'), words: ['秋天', '秋收', '明察秋毫'], sentence: '秋天到了，果子熟了。', image: 'assets/images/learn/characters/秋.png' },
      { character: '冬', pinyin: pinyin('冬'), words: ['冬天', '冬眠', '寒冬腊月'], sentence: '冬天下雪后可以堆雪人。', image: 'assets/images/learn/characters/冬.png' },
      {
        character: '风',
        pinyin: pinyin('风'),
        words: ['微风', '清风', '风和日丽'],
        sentence: '微风轻轻吹过，让人感到很舒服。',
        image: 'assets/images/learn/characters/风.png',
      }, {
        character: '云',
        pinyin: pinyin('云'),
        words: ['白云', '天空', '云雾缭绕'],
        sentence: '天空上飘着几朵白云。',
        image: 'assets/images/learn/characters/云.png',
      }, {
        character: '雨',
        pinyin: pinyin('雨'),
        words: ['雨天', '雨水', '雨打风吹'],
        sentence: '下雨了，记得打伞哦。',
        image: 'assets/images/learn/characters/雨.png',
      }, {
        character: '雪',
        pinyin: pinyin('雪'),
        words: ['雪花', '下雪', '白雪皑皑'],
        sentence: '下雪了，出去堆雪人了。',
        image: 'assets/images/learn/characters/雪.png',
      }, {
        character: '雷',
        pinyin: pinyin('雷'),
        words: ['打雷', '雷雨', '电闪雷鸣'],
        sentence: '天空乌云密布，电闪雷鸣。',
        image: 'assets/images/learn/characters/雷.png',
      }, {
        character: '雾',
        pinyin: pinyin('雾'),
        words: ['大雾', '迷雾'],
        sentence: '大雾天，我们要减速慢行。',
        image: 'assets/images/learn/characters/雾.png',
      }, {
        character: '霜',
        pinyin: pinyin('霜'),
        words: ['冰霜', '霜降', '雪上加霜'],
        sentence: '早上，门窗上起了厚厚的一层霜。',
        image: 'assets/images/learn/characters/霜.png',
      }, {
        character: '雹',
        pinyin: pinyin('雹'),
        words: ['冰雹',],
        sentence: '今天下冰雹了，地上被砸的都是小坑。',
        image: 'assets/images/learn/characters/雹.png',
      },
    ],
  },
];
